### ISSUE TITLE
What about updated OC Version?

### ISSUE THREAD

**Issue by gmraselparvez** [gxuamethyst/GA-Z270M-D3H-Hackintosh#4]
Did you update your macOS to Ventura and Opencore 0.9.5?

**Comment by gxuamethyst** [comment]
No,not yet :joy:

**Comment by gxuamethyst** [comment]
OpenCore have been update to latest version 0.9.5, macOS have been upgrade to latest version 14.0(Sonoma).
@gmraselparvez
